language: elixir

env:
  global:
  - TRAVIS=true
  - MIX_ENV=test

matrix:
  include:
    - otp_release: 20.0
      elixir: 1.5
    - otp_release: 20.0
      elixir: 1.6

before_script: mix deps.get
script: mix coveralls.travis
